<template><div v-if="store.aucation" class="space-y-6"><div class="flex items-center justify-between"><RouterLink to="/" class="text-sm font-semibold text-indigo-600">← Kembali</RouterLink><span class="badge" :class="closed?'badge-red':'badge-green'">{{closed?'Ditutup':'Berlangsung'}}</span></div><div class="grid gap-6 lg:grid-cols-5"><div class="lg:col-span-3 rounded-2xl overflow-hidden bg-white border"><img :src="store.aucation.cover||placeholder" :alt="`Cover lelang ${store.aucation.title}`" class="w-full max-h-[520px] object-cover"/></div><div class="lg:col-span-2 rounded-2xl bg-white border p-6 space-y-5"><div><h1 class="text-3xl font-bold">{{store.aucation.title}}</h1><p class="mt-2 text-sm text-slate-600">Oleh {{store.aucation.author?.name||'Pengguna'}}</p></div><div><p class="text-sm text-slate-600">Harga awal</p><p class="text-xl font-bold">{{rupiah(store.aucation.start_bid)}}</p><p class="mt-2 text-sm text-slate-600">Bid tertinggi</p><p class="text-2xl font-bold text-indigo-600">{{rupiah(highest)}}</p></div><button v-if="!isOwner && !closed" class="btn-primary w-full" @click="showBid=true">Ajukan Bid</button><button v-if="store.aucation.my_bid" class="btn-secondary w-full" @click="removeBid">Batalkan Bid Saya</button><div v-if="isOwner" class="grid grid-cols-2 gap-2"><button class="btn-secondary" @click="showChange=true">Ubah</button><button class="btn-secondary" @click="showCover=true">Ganti Cover</button><button class="col-span-2 rounded-xl bg-red-50 px-4 py-2 text-red-700 font-semibold" @click="removeAuction">Hapus Lelang</button></div></div></div><div class="grid gap-6 lg:grid-cols-3"><div class="lg:col-span-2 rounded-2xl bg-white border p-6"><h2 class="text-xl font-bold">Deskripsi</h2><MarkdownViewer class="mt-4" :text="store.aucation.description"/></div><div class="rounded-2xl bg-white border p-6"><h2 class="text-xl font-bold">Riwayat Bid</h2><div class="mt-4 space-y-3"><div v-for="bid in store.aucation.bids||[]" :key="bid.id" class="flex justify-between border-b pb-3"><span>{{rupiah(bid.bid)}}</span><span class="text-xs text-slate-600">{{date(bid.created_at)}}</span></div><p v-if="!(store.aucation.bids||[]).length" class="text-sm text-slate-600">Belum ada bid.</p></div></div></div><BidModal :open="showBid" :current="highest" @close="showBid=false" @submit="bid"/><ChangeModal :open="showChange" :item="store.aucation" :loading="store.isAucationChange" @close="showChange=false" @submit="change"/><ChangeCoverModal :open="showCover" :loading="store.isAucationChangeCover" @close="showCover=false" @submit="cover"/></div><div v-else class="rounded-2xl bg-white p-10 text-center">Memuat detail...</div></template>
<script setup>
import {computed,onMounted,ref} from 'vue';import {useRoute,useRouter} from 'vue-router';import {useAucationsStore} from '../states/aucationsStore';import {useUsersStore} from '../../users/states/usersStore';import {formatRupiah,formatDate,showConfirmDialog,showErrorDialog,showSuccessDialog} from '../../../helpers/toolsHelper';import MarkdownViewer from '../components/MarkdownViewer.vue';import BidModal from '../modals/BidModal.vue';import ChangeModal from '../modals/ChangeModal.vue';import ChangeCoverModal from '../modals/ChangeCoverModal.vue';
const route=useRoute(),router=useRouter(),store=useAucationsStore(),users=useUsersStore(),showBid=ref(false),showChange=ref(false),showCover=ref(false),placeholder='https://placehold.co/800x500?text=Delcom+Auction';const closed=computed(()=>new Date(store.aucation?.closed_at).getTime()<=Date.now());const highest=computed(()=>Math.max(Number(store.aucation?.start_bid||0),...(store.aucation?.bids||[]).map(b=>Number(b.bid||0))));const isOwner=computed(()=>store.aucation?.user_id===users.profile?.id);const rupiah=v=>formatRupiah(v),date=v=>formatDate(v);
onMounted(async()=>{await users.fetchProfile();const r=await store.fetchAucationDetail(route.params.aucationId);if(r.status!=='success')showErrorDialog('Gagal',r.message||'Lelang tidak ditemukan.')});
async function bid(v){const r=await store.addBid(route.params.aucationId,v);if(r.status==='success'){showBid.value=false;showSuccessDialog('Berhasil','Bid berhasil dikirim.');store.fetchAucationDetail(route.params.aucationId)}else showErrorDialog('Gagal',r.message||'Bid gagal dikirim.')}
async function removeBid(){const r=await store.deleteBid(route.params.aucationId);if(r.status==='success'){showSuccessDialog('Berhasil','Bid dibatalkan.');store.fetchAucationDetail(route.params.aucationId)}else showErrorDialog('Gagal',r.message||'Gagal membatalkan bid.')}
async function change(d){const r=await store.updateAucation(route.params.aucationId,d);if(r.status==='success'){showChange.value=false;showSuccessDialog('Berhasil','Lelang diperbarui.');store.fetchAucationDetail(route.params.aucationId)}else showErrorDialog('Gagal',r.message||'Gagal mengubah lelang.')}
async function cover(f){const r=await store.uploadCover(route.params.aucationId,f);if(r.status==='success'){showCover.value=false;showSuccessDialog('Berhasil','Cover diperbarui.');store.fetchAucationDetail(route.params.aucationId)}else showErrorDialog('Gagal',r.message||'Gagal mengganti cover.')}
async function removeAuction(){const c=await showConfirmDialog('Hapus lelang?','Data lelang akan dihapus.');if(!c.isConfirmed)return;const r=await store.deleteAucation(route.params.aucationId);if(r.status==='success'){showSuccessDialog('Berhasil','Lelang dihapus.');router.push('/')}else showErrorDialog('Gagal',r.message||'Gagal menghapus lelang.')}
</script>
