<template><div class="space-y-6"><div class="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4"><div><h1 class="page-title">Dashboard Lelang</h1><p class="page-subtitle">Kelola dan ikuti lelang barang dari Delcom Auction.</p></div><button class="btn-primary" @click="showAdd=true">+ Tambah Lelang</button></div>
<div class="flex flex-wrap gap-2"><button v-for="tab in tabs" :key="tab.key" class="tab" :class="activeTab===tab.key?'tab-active':''" @click="activeTab=tab.key">{{tab.label}}</button></div>
<div><input v-model="search" class="input bg-white" placeholder="Cari judul atau deskripsi lelang..."/></div>
<div v-if="store.isAucation" class="rounded-2xl bg-white p-10 text-center text-slate-500">Memuat lelang...</div><div v-else-if="!filtered.length" class="rounded-2xl bg-white p-10 text-center text-slate-500">Belum ada lelang yang sesuai.</div><div v-else class="grid gap-5 sm:grid-cols-2 xl:grid-cols-3"><article v-for="item in filtered" :key="item.id" class="overflow-hidden rounded-2xl border bg-white shadow-sm"><img :src="item.cover||placeholder" class="h-52 w-full object-cover" @error="fallback"/><div class="p-5"><div class="flex items-start justify-between gap-3"><h2 class="font-bold text-lg">{{item.title}}</h2><span class="badge" :class="isClosed(item)?'badge-red':'badge-green'">{{isClosed(item)?'Ditutup':'Berlangsung'}}</span></div><p class="mt-2 text-sm text-slate-500 line-clamp-2">{{strip(item.description)}}</p><p class="mt-4 text-sm text-slate-500">Harga awal</p><p class="font-bold text-indigo-600">{{rupiah(item.start_bid)}}</p><p class="mt-1 text-sm text-slate-500">Bid tertinggi: <b class="text-slate-800">{{rupiah(highest(item))}}</b></p><p class="mt-1 text-xs text-slate-400">Berakhir {{date(item.closed_at)}}</p><RouterLink :to="`/aucations/${item.id}`" class="btn-secondary mt-4 block text-center">Lihat Detail</RouterLink></div></article></div>
<AddModal :open="showAdd" :loading="store.isAucationAdd" @close="showAdd=false" @submit="add"/></div></template>
<script setup>
import {computed,ref,onMounted,watch} from 'vue';import {useRoute,useRouter} from 'vue-router';import {useAucationsStore} from '../states/aucationsStore';import AddModal from '../modals/AddModal.vue';import {formatRupiah,formatDate,showErrorDialog,showSuccessDialog} from '../../../helpers/toolsHelper';
const store=useAucationsStore(),route=useRoute(),router=useRouter(),search=ref(''),showAdd=ref(false),activeTab=ref(route.query.tab||'all');const tabs=[{key:'all',label:'Semua Lelang'},{key:'mine',label:'Lelang Saya'},{key:'open',label:'Lelang Berlangsung'},{key:'closed',label:'Lelang Ditutup'}];const placeholder='https://placehold.co/800x500?text=Delcom+Auction';
function isClosed(i){return new Date(i.closed_at).getTime()<=Date.now()} function highest(i){return Math.max(Number(i.start_bid||0),...(i.bids||[]).map(b=>Number(b.bid||0)))} function rupiah(v){return formatRupiah(v)} function date(v){return formatDate(v)} function strip(v){return String(v||'').replace(/[#*_`]/g,'')} function fallback(e){e.target.src=placeholder}
const filtered=computed(()=>{let a=store.aucations;if(activeTab.value==='open')a=a.filter(x=>!isClosed(x));if(activeTab.value==='closed')a=a.filter(x=>isClosed(x));const q=search.value.toLowerCase();return q?a.filter(x=>`${x.title} ${x.description}`.toLowerCase().includes(q)):a});
async function load(){const p={};if(activeTab.value==='mine')p.is_me=1;if(activeTab.value==='open')p.is_closed=1;if(activeTab.value==='closed')p.is_closed=0;const r=await store.fetchAucations(p);if(r.status!=='success')await showErrorDialog('Gagal',r.message||'Gagal mengambil data lelang.')}
watch(activeTab,(v)=>{router.replace({query:{...(v!=='all'?{tab:v}:{})}});load()});onMounted(load);
async function add(data){const r=await store.createAucation(data);if(r.status==='success'){showAdd.value=false;await showSuccessDialog('Berhasil','Lelang berhasil ditambahkan.');load()}else showErrorDialog('Gagal',r.message||'Data lelang tidak valid.')}
</script>
