<template>
  <div id="profile-page" class="space-y-6">
    <section><p class="text-xs font-bold uppercase tracking-wider text-indigo-600">Account</p><h1 class="page-title mt-1">Profil Saya</h1><p class="page-subtitle">Kelola informasi profil, foto, dan keamanan akun.</p></section>
    <div v-if="usersStore.isLoading && !usersStore.profile" class="h-96 animate-pulse rounded-3xl bg-white"></div>
    <div v-else class="grid gap-6 lg:grid-cols-3">
      <section class="rounded-3xl border border-slate-200 bg-white p-6 text-center shadow-sm"><img :src="usersStore.profile?.photo || avatar" :alt="`Foto ${usersStore.profile?.name || 'pengguna'}`" class="mx-auto h-32 w-32 rounded-full bg-slate-100 object-cover ring-4 ring-slate-50" @error="useFallback"/><h2 class="mt-5 text-xl font-extrabold">{{ usersStore.profile?.name || '-' }}</h2><p class="mt-1 text-sm text-slate-500">{{ usersStore.profile?.email || '-' }}</p><label class="mt-6 inline-flex cursor-pointer items-center rounded-xl bg-slate-100 px-4 py-3 text-sm font-bold text-slate-700 hover:bg-slate-200">{{ usersStore.isUploadingPhoto ? 'Mengunggah...' : 'Ganti Foto' }}<input class="sr-only" type="file" accept="image/*" :disabled="usersStore.isUploadingPhoto" @change="changePhoto" /></label></section>
      <div class="space-y-6 lg:col-span-2">
        <form class="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm" @submit.prevent="saveProfile"><h2 class="text-xl font-extrabold">Informasi Profil</h2><div class="mt-5 space-y-4"><div><label for="profile-name" class="label">Nama</label><input id="profile-name" v-model.trim="form.name" class="input" autocomplete="name" required /></div><div><label for="profile-email" class="label">Email</label><input id="profile-email" v-model.trim="form.email" class="input" type="email" autocomplete="email" required /></div></div><button class="btn-primary mt-5" type="submit" :disabled="usersStore.isUpdating">{{ usersStore.isUpdating ? 'Menyimpan...' : 'Simpan Perubahan' }}</button></form>
        <form class="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm" @submit.prevent="savePassword"><h2 class="text-xl font-extrabold">Keamanan Akun</h2><div class="mt-5 space-y-4"><div><label for="current-password" class="label">Password Saat Ini</label><input id="current-password" v-model="password.password" class="input" type="password" autocomplete="current-password" required /></div><div><label for="new-password" class="label">Password Baru</label><input id="new-password" v-model="password.new_password" class="input" type="password" minlength="6" autocomplete="new-password" required /></div><div><label for="confirm-password" class="label">Konfirmasi Password Baru</label><input id="confirm-password" v-model="password.new_password_confirmation" class="input" type="password" minlength="6" autocomplete="new-password" required /></div></div><button class="btn-primary mt-5" type="submit" :disabled="usersStore.isChangingPassword">{{ usersStore.isChangingPassword ? 'Memproses...' : 'Ganti Password' }}</button></form>
      </div>
    </div>
  </div>
</template>
<script setup>
import { onMounted, reactive } from 'vue'; import { useUsersStore } from '../states/usersStore'; import { showErrorDialog, showSuccessDialog } from '../../../helpers/toolsHelper';
const usersStore = useUsersStore(); const avatar = 'https://ui-avatars.com/api/?name=User&background=e2e8f0&color=334155'; const form = reactive({ name: '', email: '' }); const password = reactive({ password: '', new_password: '', new_password_confirmation: '' });
const useFallback = (e) => { e.target.src = avatar; };
onMounted(async () => { const r = await usersStore.fetchProfile(); if (r.status === 'success') Object.assign(form, { name: usersStore.profile?.name || '', email: usersStore.profile?.email || '' }); });
async function saveProfile() { const r = await usersStore.updateProfile(form); if (r.status === 'success') showSuccessDialog('Berhasil', 'Profil diperbarui.'); else showErrorDialog('Gagal', r.message || 'Gagal memperbarui profil.'); }
async function changePhoto(e) { const file = e.target.files?.[0]; if (!file) return; const r = await usersStore.uploadPhoto(file); if (r.status === 'success') showSuccessDialog('Berhasil', 'Foto profil diperbarui.'); else showErrorDialog('Gagal', r.message || 'Gagal mengunggah foto.'); e.target.value = ''; }
async function savePassword() { if (password.new_password !== password.new_password_confirmation) { showErrorDialog('Gagal', 'Konfirmasi password baru tidak sama.'); return; } const r = await usersStore.changePassword(password); if (r.status === 'success') { showSuccessDialog('Berhasil', 'Password berhasil diubah.'); Object.assign(password, { password: '', new_password: '', new_password_confirmation: '' }); } else showErrorDialog('Gagal', r.message || 'Gagal mengubah password.'); }
</script>
